# Generated by Django 4.0.2 on 2022-02-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('CourseNumber', models.IntegerField(blank=True, default='', max_length=70)),
                ('InstructorName', models.CharField(blank=True, default='', max_length=70)),
                ('Duration', models.FloatField(blank=True, default='', max_length=70)),
            ],
        ),
    ]
